-- Revert koza:init from pg

BEGIN;

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "activity" CASCADE;
DROP TABLE IF EXISTS "article" CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "rating" CASCADE;
DROP TABLE IF EXISTS "picture" CASCADE;
DROP TABLE IF EXISTS "user_rates_activity" CASCADE;
DROP TABLE IF EXISTS "activity_has_rating" CASCADE;


DROP DOMAIN IF EXISTS between_one_and_five CASCADE;
DROP DOMAIN IF EXISTS postal_code_fr CASCADE;
DROP DOMAIN IF EXISTS email_verif CASCADE;
DROP DOMAIN IF EXISTS password_verif CASCADE;

COMMIT;
