-- Revert koza:init from pg

BEGIN;

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "activity" CASCADE;
DROP TABLE IF EXISTS "article" CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "rating" CASCADE;
DROP TABLE IF EXISTS "picture" CASCADE;
DROP TABLE IF EXISTS "user_rates_activity" CASCADE;
DROP TABLE IF EXISTS "activity_has_rating" CASCADE;



COMMIT;
